# This is a basic workflow to help you get started with Actions

name: ssh

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      NPC_HOST_IP: ${{ secrets.NPC_HOST_IP }}
      NPC_HOST_PORT: ${{ secrets.NPC_HOST_PORT }}
      NPC_VKEY: ${{ secrets.NPC_VKEY }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: download nps        
        run: 
          wget https://github.com/ehang-io/nps/releases/download/v0.26.8/linux_amd64_client.tar.gz
          
      - name: run nps
        run: |
          tar xvf linux_amd64_client.tar.gz &&
          echo NPC_HOST_IP:$NPC_HOST_IP
          #nohup echo 'Done' 2>&1 &
          nohup ./npc -server=$NPC_HOST_IP:$NPC_HOST_PORT -vkey=$NPC_VKEY -type=tcp  >> /tmp/nohup.log 2>&1 &
          echo 'Done'

      # Runs a single command using the runners shell
      - name: Setup Debug Session
        uses: newrey/debugger-action@master
